### ISSUE TITLE
Add LICENSE file

### ISSUE THREAD

**Issue by opalrose510** [JanessaMunt/Swap#1]
Hi there!

Thank you for coming to the hackathon :heart: I had a wonderful time, I hope you did too :)

Could you please add a LICENSE file of your choice to this so I can add it to our gather-examples repo? I want to make sure it stays as your IP / we keep in mind whatever licensing terms you prefer.

- opalrose

**Comment by JanessaMunt** [comment]
@evelyn-f-king It was so much fun! License added!
